Complete CSV Generator
rpt23-sdc-horror/service-inventory-module pull request #5
Opened 2020-11-29 07:29 UTC by martinsung00

**Size:** XL
**Related Trello Cards:** [card one](https://trello.com/c/o5FaIweM), [card two](https://trello.com/c/MB6NdyDD)
Change(s):

Revise Seeder Script (now an sql file)
Create Data Generator
Create Example in vault
Create Example in seed_data
Create Temporary SH bootstrap file
Update package.json
Update front-end slightly to successfully retrieve items from database
Update server routes to server parsed response
Update tests to reflect changes
Prune unnecessary code

**Notes:**
Successfully generated 10 million records and seed database

2020-11-29 07:32 UTC, martinsung00 commented on seeder/postgres_seeder/data_generator/config.js
> +  product_range: 95239,
**Annotation:** 95,239 products equate to 10+ million records as it branches into 7 different styles and each style branches off into 15 or 17 sizes depending on gender.

2020-11-29 07:35 UTC, martinsung00 commented on seeder/postgres_seeder/data_generator/seed_data/sample.csv
> +product_id, style_id, size, quantity
**Annotation:** This is just an example file for anyone else who gets this repository.

2020-11-29 07:38 UTC, martinsung00 commented on src/controller/logger.js
> +import winston from "winston";
**Annotation:** Created a Winston logger specifically for controllers.

2020-11-29 07:39 UTC, martinsung00 commented on src/controller/plugin.js
> -      this.gateway.logger.log("error", "Error:", err);
**Annotation:** Controllers should not be using gateway's logger, but it's own logger.

2020-11-29 07:39 UTC, martinsung00 commented on src/gateways/schema/schema.sql
> +  product_id varchar(50000) NOT NULL,
**Annotation:** Testing limits.

2020-11-29 07:40 UTC, martinsung00 commented on src/server/routes.js
> +      res.send(result.rows).status(200);
**Annotation:** Update server to serve array of information directly.

2020-11-29 10:13 UTC, TandyN requested changes
Assuming that changing the API response to rows didn't break anything in the front end, I see no conflicts in functionality.

1 very minor suggestion was made in a file. Also, you've committed your bundle file unless that was intentional? if so, please explain. If not, please remove.

2020-11-29 10:13 UTC, TandyN commented on seeder/postgres_seeder/data_generator/plugin.js
> +  }
Could technically return the results right away. At least I think its just as readable in 1 line.

2020-11-29 20:30 UTC, martinsung00 commented on seeder/postgres_seeder/data_generator/plugin.js
> +  }
Fixed it to return statement instead of variable.

2020-11-29 20:31 UTC, martinsung00 commented on seeder/postgres_seeder/data_generator/plugin.js
> +  }
Fixed the gitignore not working properly with bundle.js; now it's fully ignored. The front-end works with the new changes in the server; made some slight edits beforehand.

2020-11-30 15:49 UTC, TandyN approved these changes
Requested changes have been applied. Please squash your commits.

2020-11-30 19:35 UTC, merged

2020-12-02 02:41 UTC, LesliePajuelo commented
@martinsung00 hi! Martin you've had several large PRs! This is no longer acceptable. Come to office hours for help on how to manage your git workflow.